config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :phone_number, uniqueness: true, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'reviews/new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="container">
        <%= yield %>
    </div>
</body>

</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>

<div class="restaurant">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES %>
    <%= f.button :submit, class: "btn btn-primary" %>
    </div>
    </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="container">
<p id="notice">
    <%= notice %>
</p>
<h1>Restaurants</h1>
<div class="custom-border-top"></div>
<br>
<%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-primary" %>
<% @restaurants.each do |restaurant| %>
<div class="card-product">
    <img src="https://source.unsplash.com/featured/?restaurant, <%= restaurant.category %>" />
    <div class="card-product-infos">
        <h2>
            <%= restaurant.name %>
        </h2>
        <p>
            <%= restaurant.address %>
            <%= restaurant.category %>
            <%= restaurant.category %>
        </p>
    </div>
    <div class="btn-all">
        <%= link_to 'Show', restaurant, class: "btn" %>
        <%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn" %>
        <%= link_to 'Destroy', restaurant, class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
</div>
<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<div class="custom-border-top"></div>
<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<div>
  <% @restaurant.reviews.each do |review| %>
    <div class="border-top">
      <p><%= review.content %></p>
      <p><%= '🦴' * review.rating %></p>
      <p><%= review.created_at %></p>
    </div>
  <% end %>
</div>

<%= link_to 'Add Review', new_restaurant_review_path(@restaurant) %> |
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Create new review</h1>

<%= render 'form' %>